---
title: "STAT585_LAB3"
author: "Team 4"
output:
  html_document:
    keep_md: True
---

## Link
[https://github.com/lydiaPenglish/smoothMap](https://github.com/lydiaPenglish/smoothMap)

## Team Members
- Lydia English
- Yang Qiao
- Xiyuan Sun

```{r setup, include = FALSE}
knitr::opts_chunk$set(warning = F, message = F, fig.align = "center")
```

## Description
The goal of `smoothMap` is to generate a function to help map files.

## Installation
You can install the released version of Mygit from [Github](https://github.com/lydiaPenglish/smoothMap) with:
``` r
devtools::install_github("lydiaPenglish/smoothMap")
```

## Example
This is a basic example which shows you how to use the functions in `smoothMap`:

```{r example}
library(smoothMap)
library(ggplot2)

mex_file <- system.file("extdata", "gadm36_MEX_1.shp", package = "smoothMap")
mex_data <- team_1(mex_file, tolerance = 0.05)
ggplot(mex_data, aes(x = long, y = lat, group = group)) +
  geom_polygon(color = "black", fill = "white", size = 0.2) +
  labs(x = "Longitude", y = "Latitude", title = "Mexico") +
  coord_fixed() +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))

pan_file <- system.file("extdata", "gadm36_PAN_1.shp", package = "smoothMap")
pan_data <- team_4(pan_file, tolerance = 0.01)
ggplot(pan_data, aes(x = long, y = lat, group = group)) +
  geom_polygon(color = "black", fill = "white", size = 0.2) +
  labs(x = "Longitude", y = "Latitude", title = "Panama") +
  coord_fixed() +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))
```
